### ISSUE TITLE
Network error LED not functional.

### ISSUE THREAD

**Issue by andrew-axiom** [ColquhounAudio/AxiomBuild#7] opened 2018-08-22 17:56 UTC
When a configured WiFi network cannot be found, the network error LED (LED2/MCP23017 GPB4) should blink.

**Comment by ggiraudon** [comment] 2018-08-24 09:25
Issue was caused by a miss-ordering of services. This should now be resolved in the next release.

**Comment by ggiraudon** [comment] 2018-08-24 09:27
Issue should be fixed by 6677302295d3d081ffdde08fe3392abf89fb8705

**Comment by andrew-axiom** [comment] 2018-08-24 15:10
Still not working, even after a reboot.

**Closed as completed** 2018-09-07 13:36 UTC
Labels: bug
