### ISSUE TITLE
WAC

### ISSUE THREAD

**Issue by AxiomSteve** [ColquhounAudio/AxiomBuild#2] opened 2018-08-22 15:14 UTC
An unexpected error has occurred (Fails MFi). Does connect to network after an extended wait time

**Comment by ggiraudon** [comment] 2018-08-24 10:00
This issue could be resolved.
The reason I'm unsure is because it may have had to do with the QC check script that wasnt running on first start.
Will have to retest on next image

**Comment by AxiomSteve** [comment] 2018-08-24 11:39
WAC is no longer broadcasting at all

**Comment by andrew-axiom** [comment] 2018-08-24 14:06
I can confirm no WAC. Also, the WiFi indicator LED does not begin "fast flashing" to indicate WAC.

**Comment by andrew-axiom** [comment] 2018-08-24 14:16
I also noticed that after connecting to the hotspot and then putting it on my home network the network settings do not seem to be automatically reset. I needed to power the unit on and off and before the blue WiFi LED lit up the red network error LED flashed a few times. Finally, axiomair.local/ does not seem to be resolving.

**Comment by andrew-axiom** [comment] 2018-09-11 18:11
2018-09-10 WAC is still giving "an unexpected error occurred" during setup, even though the device connects to the network. There is an auto restart that happens after the network is configured and the start-up sound is cut off abruptly after a second.

**Comment by ggiraudon** [comment] 2018-09-11 21:39
This could possibly be resolved on Toasted Sesame.
Please try a bare metal install with https://s3.amazonaws.com/axiom-air-install-files/AxiomAirV2/v1.0/AxiomAirV2.02-Toasted-Sesame-2018-09-11-pi.img.zip

**Comment by AxiomSteve** [comment] 2018-09-12 12:54
Using fresh "Toasted Sesame" WAC failed completely. Rebooted 2 times before it would connect to network but still gave "unexpected error"

**Comment by IanColquhoun** [comment] 2018-09-19 05:30
On Toasted Peanut the only issue I can find with WAC is that sometimes, I would guess at around half the time, you get an error message on the Apple device saying there was an error putting the AirPlay speaker on the network even though it did indeed put it on the network.

**Closed as completed** 2018-10-19 14:30 UTC
Labels: Affects both v1 and v2
