### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by AxiomSteve** [ColquhounAudio/AxiomBuild#1] opened 2018-08-22 15:11 UTC
No volume control from UI or hardware input buttons. Volume slider does respond to hardware buttons properly.

**Comment by ggiraudon** [comment] 2018-08-24 09:56
Should be resolved in the new release.
Problem is caused by clusterfuck of device labeling and usage accross volumio.
This issue is patched but will need to be revisited for better resolution.

**Comment by AxiomSteve** [comment] 2018-08-24 11:45
Sorry still not working

**Comment by andrew-axiom** [comment] 2018-08-24 14:20
Neither slider or buttons are working. The mute button is also not functional.

**Closed as completed** 2018-09-07 13:21 UTC
Labels: bug, enhancement, Priority HIGHEST
